// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations;

#nullable disable

namespace Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211212170429_AddPictureId")]
    partial class AddPictureId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("Domain.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "John Doe is a fictional character and the main protagonist of the fictional series The Walking Dead.",
                            DateOfBirth = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            Picture = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/John_Doe_%28The_Walking_Dead%29.png/220px-John_Doe_%28The_Walking_Dead%29.png",
                            PictureId = "qi9zcoygcctcpmqobyah"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Rick Grimes is a fictional character and the main protagonist of the fictional series The Walking Dead.",
                            DateOfBirth = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rick Grimes",
                            Picture = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/John_Doe_%28The_Walking_Dead%29.png/220px-John_Doe_%28The_Walking_Dead%29.png",
                            PictureId = "qi9zcoygcctcpmqobyah"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Michonne is a fictional character and the main protagonist of the fictional series The Walking Dead.",
                            DateOfBirth = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michonne",
                            Picture = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/John_Doe_%28The_Walking_Dead%29.png/220px-John_Doe_%28The_Walking_Dead%29.png",
                            PictureId = "qi9zcoygcctcpmqobyah"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Glenn Rhee is a fictional character and the main protagonist of the fictional series The Walking Dead.",
                            DateOfBirth = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Glenn Rhee",
                            Picture = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/John_Doe_%28The_Walking_Dead%29.png/220px-John_Doe_%28The_Walking_Dead%29.png",
                            PictureId = "qi9zcoygcctcpmqobyah"
                        });
                });

            modelBuilder.Entity("Domain.Data.Entities.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
